### ISSUE TITLE
plot a figure to estimate speed of cars

### ISSUE THREAD

**Issue by assalas06-bejaia** [fkthi/OpenTrafficMonitoringPlus#5]
how I could draw the figures on the estimated speeds for a video that is not present on your base, just to see the evolution of the speed throughout the frames.
otherwise generate a file relative to the displacement of the pixels.
and how did you calculate the homography and estimate the speed ?

I thank you in advance for your return

**Comment by fkthi** [comment]
All computed state variables can be stored as csv / json/txt/pickle file as export, see config.py. This includes the speed of each vehicle tracked. You can plot the data from these files with any tool you prefer. The state variables are estimated with a Kalman Filter. Please check our publications for more information.

**Comment by assalas06-bejaia** [comment]
But to estimate the velocity, you have used the homography matrix, could you tell me which points are selected to apply the homography?

On the set of tests that you had carried out, what is the error of the estimation. 
I thank you again for your responsiveness.
