### ISSUE TITLE
Can I replace Mask CNN with YOLOV4

### ISSUE THREAD

**Issue by assalas06-bejaia** [fkthi/OpenTrafficMonitoringPlus#6]
how I can replace mask cnn with yolov4 

thank you in advance

**Comment by fkthi** [comment]
Generally, you can replace the detection with other networks. The pipeline (pre-processing, detection, post-prosseing) is modular. But, YOLO only provides non-rotated bounding boxes. In our approach we obtain the vehicle orientation from the segmentation masks (see our publications), which you cannot do you with the standard YOLO network. If your YOLO implementation outputs oriented bounding boxes (including the orientation angle), replacing the detector should be pretty straight forward.
